version: '3.5'
services:
  fit-friends.workouts.postgres:
    image: postgres:14-alpine
    container_name: fit-friends.workouts.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: fit-friends
    ports:
      - 5432:5432
    volumes:
      - fit-friends.postgres.workouts:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - fit-friends.workouts

  typoteka.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: fit-friends.workouts.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "dimk@mailme.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - fit-friends.workouts

volumes:
  fit-friends.postgres.workouts:

networks:
  fit-friends.workouts:
    driver: bridge
