# Create a new common-user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "commonuser@example.com",
  "fitnessLevel": "beginner",
  "gender": "male",
  "location": "Moscow",
  "name": "Common User",
  "description": "I'm a regular user",
  "birthDate": "1992-06-17",
  "password": "commonuserpassword",
  "role": "User",
  "workoutTypes": ["yoga", "strength"],
  "avatarImage": "avatar_image_url",
  "pageImage": "page_image_url",
  "workoutTime": "morning",
  "dailyCalorieBurn": 2000,
  "calorieBurnGoal": 2500,
  "readyToTrain": true
}

###

# Create a new trainer-user
POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "traineruser@example.com",
  "fitnessLevel": "professional",
  "gender": "female",
  "location": "Saint Petersburg",
  "name": "Trainer User",
  "description": "I'm a professional trainer",
  "birthDate": "1989-11-21",
  "password": "traineruserpassword",
  "role": "Trainer",
  "workoutTypes": ["cardio", "yoga"],
  "avatarImage": "avatar_image_url",
  "pageImage": "page_image_url",
  "certificates": ["Certificate 1", "Certificate 2"],
  "achievements": "Won fitness trainer of the year 2022",
  "readyForPersonalTraining": true
}

###

# Get user by ID
GET http://localhost:3000/api/auth/b42a52ba-8012-4be8-9b8c-6ddaa78a6f42 HTTP/1.1

###

# Login user by email and password
POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "traineruser@example.com",
  "password": "traineruserpassword"
}

###
